# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

print ('@@@@@  @      @  @@     @       @')
print ('    @  @      @  @ @    @      @ @')
print ('    @  @      @  @  @   @     @   @')
print ('    @  @      @  @   @  @    @@@@@@@')
print ('   @   @      @  @    @ @   @       @')
print ('  @      @@@@    @     @@  @         @\n')
print('========== ELKOM 1 ==========\n')
print('Tanggal : selasa, 12 desember 2023\n')
mahasiswa=[]
def data_masuk():
   nama  = input("Masukkan nama mahasiswa: ")
   nilai1=int(input("Masukkan Nilai Prak 1: "))
   nilai2=int(input("Masukkan Nilai Prak 2: "))
   nilai3=int(input("Masukkan Nilai Prak 3: "))
   list=[nama,nilai1,nilai2,nilai3]
   mahasiswa.insert(len(mahasiswa),list)
   main()
def data():
    print(" NAMA |","PRAK 1|","PRAK 2|","PRAK 3|")
    for i in mahasiswa:
        print(i[0],"\t",i[1],"\t",i[2],"\t",i[3])
    main()
def nilaimahasiswa():
    for i in range(len(mahasiswa)):
        total=0
        for j in range (1,len(mahasiswa[i])):
            total+=mahasiswa[i][j]
        print(mahasiswa[i][0],"=",total/len(mahasiswa[i]))
    main()
def nilaipraktikum():
    praktikum1=0
    praktikum2=0
    praktikum3=0
    for i in range(len(mahasiswa)):
        praktikum1+=mahasiswa[i][1]
        praktikum2+=mahasiswa[i][2]
        praktikum3+=mahasiswa[i][3]
    praktikum1=praktikum1/len(mahasiswa)
    praktikum2=praktikum2/len(mahasiswa)
    praktikum3=praktikum3/len(mahasiswa)
    print("Nilai prak rata-rata 1= ",praktikum1)
    print("Nilai prak rata-rata 2= ",praktikum2)
    print("nilai prakrata-rata 3= ",praktikum3)
    main()
def nilairatarata():
    nilaimahasiswa=[]
    total=0
    for i in range(len(mahasiswa)):
        total=0
        for x in range (1,len(mahasiswa[i])):
            total+=mahasiswa[i][x]
        nilaimahasiswa.insert(len(nilaimahasiswa),total/5)
    total=0
    for i in nilaimahasiswa:
        total+=i
    total=total/len(nilaimahasiswa)
    print(total)
    main()
def update_nilai():
    update=input("Nilai Nama Mahasiswa Yang Ingin Direvisi :")
    nilai=int(input("Nilai Yang Ingin Di Revisi Pada Praktikum ke-: "))
    nilai_baru=int(input("Nilai Baru: "))
    for i in mahasiswa:
        if i [0]==update:
            i[nilai]=nilai_baru
    main()
def main():
    print("Program Membuat List")
    print("1.Memasukkan nama dan nilai")
    print("2.Lihat data")
    print("3.Nilai rata-rata pada mahasiswa")
    print("4.Nilai rata-rata setiap praktikum mahasiswa")
    print("5.Mencari nilai rata-rata dari setiap mahasiswa")
    print("6.Mengubah nilai mahasiswa")
    print("7.Keluar")
    pilih=int(input("Ketik angka 1 - 7(ketik 7 jika sudah selesai):"))
    if pilih==1:
        data_masuk()
    elif pilih==2:
        data()
    elif pilih==3:
        nilaimahasiswa()
    elif pilih==4:
        nilaipraktikum()
    elif pilih==5:
        nilairatarata()
    elif pilih==6:
        update_nilai()
    elif pilih==7:
        exit()
    else:
        print("Keyword yang kamu masukin salah bro :( ")
        pilih=int(input("Ketik angka 1 - 7 (ketik 7 jika sudah selesai):"))
main()